resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm
  - repository: aomp_repo
    type: github
    endpoint: ROCm
    name: ROCm/aomp
    ref: aomp-dev

variables:
- group: common
- template: /.azuredevops/variables-global.yml@pipelines_repo

trigger:
  batch: true
  branches:
    include:
    - aomp-dev
  paths:
    exclude:
    - .github
    - LICENSE

pr:
  autoCancel: true
  branches:
    include:
    - develop
  paths:
    exclude:
    - .github
    - LICENSE
  drafts: false

jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/aomp-extras.yml@pipelines_repo
